---
name: InventoryMonitor
main: kim\present\inventorymonitor\InventoryMonitor
version: 1.2.0
api: [3.1.1]
author: PresentKim
website: https://github.com/PresentKim/InventoryMonitor-PMMP
description: Monitoring player inventory

permissions:
  inventorymonitor.cmd:
    description: Open player inventory
    default: op
...
